# Generated by Django 5.1.4 on 2024-12-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nomi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/photo/')),
                ('information', models.TextField(verbose_name="ma'lumot")),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nomi')),
                ('type', models.CharField(max_length=25, verbose_name='turi')),
                ('information', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='car/photo/')),
                ('release_date', models.DateTimeField(auto_now=True, verbose_name='Chiqarilgan sana')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
            ],
        ),
    ]
